services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=medilabo'
      - 'MYSQL_USER=medilabo'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
    ports:
      - '3307:3306'