CREATE TABLE patient
(
    ID              INT PRIMARY KEY,
    LAST_NAME       VARCHAR(255) NOT NULL,
    FIRST_NAME      VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH   DATE NOT NULL,
    GENDER          VARCHAR(255) NOT NULL,
    ADDRESS         VARCHAR(255),
    PHONE_NUMBER    VARCHAR(255)
);
