server.port=9001

spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

management.endpoint.gateway.enabled=true
# À désactiver en production
# management.endpoints.web.exposure.include=gateway
management.endpoints.web.exposure.include=health,info
