app.mongodb.host=${MONGO_HOST:localhost}
app.mongodb.port=${MONGO_PORT:27017}
app.mongodb.username=${MONGO_USERNAME:user}
app.mongodb.password=${MONGO_PASSWORD:pass}
app.mongodb.database=${MONGO_DATABASE:medilabo}
